# Log Node.js Applications

# Here you may configure the log channels for your application. Out of
# the box, mern-boilerplate uses the Winston PHP logging library. This gives
# you a variety of powerful log handlers / formatters to utilize.
# level: error, warn, info, verbose, debug, silly

exitOnError:

file:
  level:
  filename:
  handleExceptions:
  json:
  maxsize:
  maxFiles:
  colorize:


console:
  level:
  handleExceptions:
  json:
  colorize:
